export const  ROTA_LOTOFACIL = "Lotofácil"
export const  ROTA_MEGA = "Mega sena"
export const  ROTA_QUINA = "Quina"
export const  ROTA_LOTOMANIA = "Lotomania"
export const  ROTA_RESULTADOS = "Resultados"